# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 81c9c13f4eee7f4ee8643036aafa0c50945652a3a9797d7bbc4730221298e5e1379f115414ef42fe5832c76b005dbdc4ef02d5c2aee9d631bcae6bdf78e3bb7c

test:
  secret_key_base: 47c8f1177ab88549e1c573de29d1d92ec2112df13f5395a101d83c1316b146d1e15959ab0d08287873f553336b8840c9745ea4c3a9274e31da42150003e3fe47

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
